// Hand-authored display config: labels + Front/Back grouping + per-game theming.
//
// This is the one thing NOT derivable from the folder tree — the human labels
// ("Mr Shadow's Covers (Favorite)") and the front/back split live only in the
// old landing HTML. Image lists themselves come from app/data/manifest.json
// (generated by scripts/build-manifest.mjs from the assets/ folder).
//
// Adding new upstream IMAGES to an existing set needs no change here (they flow
// in via the manifest). A brand-new SET or GAME needs a one-line entry below.

export interface SetLink {
  /** Exact folder name under assets/<dir>/<type>/ — also the [set] route param. */
  set: string
  label: string
}

export interface Game {
  id: string
  /** Top-level folder under assets/ */
  dir: string
  title: string
  /** Background image served from /images */
  bg: string
  /** Accent colour (matches the old per-game button colour) */
  color: string
  cards: { front: SetLink[]; back: SetLink[] }
  coins: { front: SetLink[]; back: SetLink[] }
}

export const games: Game[] = [
  {
    id: 'spyro',
    dir: '01_Spyro',
    title: "Spyro's Adventure",
    bg: '/images/spyro.webp',
    color: '#0aa808',
    cards: {
      front: [
        { set: 'Mr_Shadow', label: "Mr Shadow's Covers (Favorite)" },
        { set: 'Sobersu_Logo', label: "Sobersu's Covers (Logo)" },
        { set: 'Sobersu_Stats', label: "Sobersu's Covers (Stats)" },
        { set: 'Adri-Dani_Clean', label: "Adri-Dani's Covers (Clean)" },
        { set: 'Adrian_Pokemon', label: "Adrian's Covers (Pokemon)" },
      ],
      back: [
        { set: 'Back_Covers_Var_1', label: 'Card Back Covers (Logo)' },
        { set: 'Back_Covers_Var_2', label: 'Card Back Covers (Poster)' },
      ],
    },
    coins: {
      front: [
        { set: 'Mirakel_Clean', label: "Mirakel's Round Covers (Clean)" },
        { set: 'Mirakel_Logo', label: "Mirakel's Round Covers (Logo)" },
        { set: 'Sobersu_Clean', label: "Sobersu's Round Covers (Clean)" },
        { set: 'Sobersu_Close', label: "Sobersu's Round Covers (Close)" },
        { set: 'Cha0s_Logo', label: "Cha0s's Round Covers (Chase)" },
      ],
      back: [
        { set: 'Sobersu_Back', label: "Sobersu's Back Covers (Logo)" },
        { set: 'Cha0s_Logo_Back', label: "Cha0s's Back Covers (Chase)" },
        { set: 'Back_Covers', label: 'Round Back Covers (Logo)' },
      ],
    },
  },
  {
    id: 'giants',
    dir: '02_Giants',
    title: 'Giants',
    bg: '/images/giants.webp',
    color: '#FB7600',
    cards: {
      front: [
        { set: 'Mr_Shadow', label: "Mr Shadow's Covers (Favorite)" },
        { set: 'Sobersu_Logo', label: "Sobersu's Covers (Logo)" },
        { set: 'Sobersu_Stats', label: "Sobersu's Covers (Stats)" },
        { set: 'Adri-Dani_Clean', label: 'Adri-Dani Covers (Clean)' },
      ],
      back: [
        { set: 'Back_Covers_Var_1', label: 'Card Back Covers (Logo)' },
        { set: 'Back_Covers_Var_2', label: 'Card Back Covers (Poster)' },
      ],
    },
    coins: {
      front: [
        { set: 'Mirakel_Clean', label: "Mirakel's Round Covers (Clean)" },
        { set: 'Mirakel_Logo', label: "Mirakel's Round Covers (Logo)" },
        { set: 'Sobersu_Clean', label: "Sobersu's Round Covers (Clean)" },
        { set: 'Sobersu_Close', label: "Sobersu's Round Covers (Close)" },
        { set: 'Cha0s_Logo', label: "Cha0s's Round Covers (Chase)" },
      ],
      back: [
        { set: 'Sobersu_Back', label: "Sobersu's Back Covers (Logo)" },
        { set: 'Fruitsnack_Back', label: "Fruitsnack's Back Covers (Logo)" },
        { set: 'Cha0s_Back', label: "Cha0s's Back Covers (Logo)" },
        { set: 'Back_Covers', label: 'Round Back Covers (Logo)' },
      ],
    },
  },
  {
    id: 'swapforce',
    dir: '03_Swap_Force',
    title: 'Swap Force',
    bg: '/images/swapforce.webp',
    color: '#1888c8',
    cards: {
      front: [
        { set: 'Mr_Shadow', label: "Mr Shadow's Covers (Favorite)" },
        { set: 'Adri-Dani_Clean', label: "Adri-Dani's Covers (Clean)" },
      ],
      back: [
        { set: 'Back_Covers_Var_1', label: 'Card Back Covers (Logo)' },
        { set: 'Back_Covers_Var_2', label: 'Card Back Covers (Poster)' },
      ],
    },
    coins: {
      front: [
        { set: 'Mirakel_Clean', label: "Mirakel's Round Covers (Clean)" },
        { set: 'Mirakel_Logo', label: "Mirakel's Round Covers (Logo)" },
        { set: 'Fruitsnack_Clean', label: "Fruitsnack's Covers (Clean)" },
      ],
      back: [
        { set: 'Fruitsnack_Back', label: "Fruitsnack's Back Covers (Logo)" },
        { set: 'Back_Covers', label: 'Round Back Covers (Logo)' },
      ],
    },
  },
  {
    id: 'trapteam',
    dir: '04_Trap_Team',
    title: 'Trap Team',
    bg: '/images/trapteam.webp',
    color: '#FE0000',
    cards: {
      front: [
        { set: 'Mr_Shadow', label: "Mr Shadow's Covers (Favorite)" },
        { set: 'Sobersu_Logo', label: "Sobersu's Covers (Logo)" },
        { set: 'Sobersu_Stats', label: "Sobersu's Covers (Stats)" },
        { set: 'Dim_Logo', label: "Dim's Villains Covers (Logo)" },
        { set: 'Adri-Dani_Clean', label: "Adri-Dani's Covers (Clean)" },
      ],
      back: [
        { set: 'Back_Covers_Var_1', label: 'Card Back Covers (Logo)' },
        { set: 'Back_Covers_Var_2', label: 'Card Back Covers (Poster)' },
      ],
    },
    coins: {
      front: [
        { set: 'Mirakel_Clean', label: "Mirakel's Round Covers (Clean)" },
        { set: 'Mirakel_Logo', label: "Mirakel's Round Covers (Logo)" },
        { set: 'Sobersu_Clean', label: "Sobersu's Round Covers (Clean)" },
        { set: 'Sobersu_Close', label: "Sobersu's Round Covers (Close)" },
      ],
      back: [
        { set: 'Sobersu_Back', label: "Sobersu's Back Covers (Logo)" },
        { set: 'Fruitsnack_Back', label: "Fruitsnack's Covers (Logo)" },
        { set: 'Back_Covers', label: 'Round Back Covers (Logo)' },
      ],
    },
  },
  {
    id: 'superchargers',
    dir: '05_SuperChargers',
    title: 'SuperChargers',
    bg: '/images/superchargers.webp',
    color: '#99722D',
    cards: {
      front: [
        { set: 'Mr_Shadow', label: "Mr Shadow's Covers (Favorite)" },
        { set: 'Mr_Shadow_SuperCharged', label: "Mr Shadow's SuperCharged" },
        { set: 'Adri-Dani_Clean', label: "Adri-Dani's Covers (Clean)" },
        { set: 'AlexDTI_Stats', label: "AlexDTI's Covers (Stats)" },
        { set: 'LenLen_Logo', label: "LenLen's Covers (Logo)" },
        { set: 'Sobersu_Clean', label: "Sobersu's Covers (Clean)" },
      ],
      back: [
        { set: 'Back_Covers_Var_1', label: 'Card Back Covers (Logo)' },
        { set: 'Back_Covers_Var_2', label: 'Card Back Covers (Poster)' },
      ],
    },
    coins: {
      front: [
        { set: 'Mirakel_Clean', label: "Mirakel's Round Covers (Clean)" },
        { set: 'Mirakel_Logo', label: "Mirakel's Round Covers (Logo)" },
        { set: 'Fruitsnack_Clean', label: "Fruitsnack's Covers (Clean)" },
      ],
      back: [
        { set: 'Fruitsnack_Back', label: "Fruitsnack's Back Covers (Logo)" },
        { set: 'Back_Covers', label: 'Round Back Covers (Logo)' },
      ],
    },
  },
  {
    id: 'imaginators',
    dir: '06_Imaginators',
    title: 'Imaginators',
    bg: '/images/imaginators.webp',
    color: '#570E77',
    cards: {
      front: [
        { set: 'Mr_Shadow', label: "Mr Shadow's Covers (Favorite)" },
        { set: 'Mr_Shadow_Crystals', label: "Mr Shadow's Crystals (Empty)" },
        { set: 'SkylandersNFC_Logo', label: "SkylandersNFC's Covers (Logo)" },
        { set: 'Sobersu_Logo', label: "Sobersu's Covers (Logo)" },
        { set: 'Sobersu_Stats', label: "Sobersu's Covers (Stats)" },
        { set: 'Adri-Dani_Clean', label: "Adri-Dani's Covers (Clean)" },
        { set: 'AlexDTI_Stats', label: "AlexDTI's Covers (Stats)" },
        { set: 'Cendrillion_Clean', label: "Cendrillion's Covers (Clean)" },
        { set: 'IndominusRex_Clean', label: "IndominusRex's Covers (Clean)" },
        { set: 'Mejoe_Logo', label: "Mejoe's Covers (Logo)" },
      ],
      back: [
        { set: 'Cendrillion_Back', label: "Cendrillion's Covers (Back)" },
        { set: 'Back_Covers_Var_1', label: 'Card Back Covers (Logo)' },
        { set: 'Back_Covers_Var_2', label: 'Card Back Covers (Poster)' },
      ],
    },
    coins: {
      front: [
        { set: 'Mirakel_Clean', label: "Mirakel's Round Covers (Clean)" },
        { set: 'Mirakel_Logo', label: "Mirakel's Round Covers (Logo)" },
        { set: 'SkylandersNFC_Clean', label: "SkylandersNFC's Covers (Clean)" },
        { set: 'SkylandersNFC_Logo', label: "SkylandersNFC's Covers (Logo)" },
        { set: 'Sobersu_Clean', label: "Sobersu's Covers (Clean)" },
        { set: 'Sobersu_Close', label: "Sobersu's Covers (Close)" },
        { set: 'Cha0s_Variants', label: "Cha0s's Variant Covers" },
      ],
      back: [
        { set: 'Mirakel_Back', label: "Mirakel's Back Covers (Logo)" },
        { set: 'Shizzy_Back', label: "Shizzy's Back Covers (Logo)" },
        { set: 'Sobersu_Back', label: "Sobersu's Back Covers (Logo)" },
        { set: 'Back_Covers', label: 'Round Back Covers (Logo)' },
      ],
    },
  },
]

export const gamesById: Record<string, Game> = Object.fromEntries(
  games.map((g) => [g.id, g]),
)
